---
# echo https://raw.githubusercontent.com/ds-jenkins-course/jobdsl/$(git rev-parse HEAD)/jenkins.yaml | pbcopy

jenkins:
  systemMessage: "Nazdar"

jobs:
  - script: >
      folder("_RESENI")
  - script: >
      job('_RESENI/bootstrap') {
        scm {
          git {
            remote {
              github("ds-jenkins-course/jobdsl")
            }
          } 
        }
        steps {
          dsl(
            [
              'Jenkins-pro-Vyvojare/x00_bootstrap.groovy'
            ], 
            'DELETE'
            )
        }
      }
