---
# echo https://raw.githubusercontent.com/ds-jenkins-course/jobdsl/$(git rev-parse HEAD)/jenkins.yaml | pbcopy

jenkins:
  systemMessage: "Nazdar"

jobs:
  - script: >
      folder("_RESENI")
  - script: >
      job('_RESENI/bootstrap') {
          git("https://github.com/ds-jenkins-course/jobdsl.git")
          steps {
              dsl([
                  'Jenkins-pro-Vyvojare/00_bootstrap.groovy'
                  ], 'DELETE')
          }
      }
