---
# paste to: http://lab-instance:8000/configuration-as-code/

# echo https://raw.githubusercontent.com/ds-jenkins-course/jobdsl/$(git rev-parse HEAD)/jenkins.yaml | pbcopy

jobs:
  - script: >
      folder("_LABS")
  - script: >
      job('_LABS/bootstrap') {
        scm {
          git {
            remote {
              github("ds-jenkins-course/jobdsl")
            }
          } 
        }
        steps {
          dsl(
            [
              'jobs/bootstrap.groovy'
            ], 
            'DELETE'
            )
        }
      }

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - name: "OpenJDK 8"
      properties:
      - installSource:
          installers:
          - adoptOpenJdkInstaller:
              id: "jdk8u312-b07"
    - name: "OpenJDK 11"
      properties:
      - installSource:
          installers:
          - adoptOpenJdkInstaller:
              id: "jdk-11.0.13+8"
  maven:
    installations:
    - name: "Maven 3.3.9"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.3.9"
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.8.4"
