---
# paste to: http://lab-instance:8000/configuration-as-code/

# echo https://raw.githubusercontent.com/ds-jenkins-course/jobdsl/$(git rev-parse HEAD)/jenkins.yaml | pbcopy

jobs:
  - script: >
      folder("_LABS")
  - script: >
      job('_LABS/bootstrap') {
        scm {
          git {
            remote {
              github("ds-jenkins-course/jobdsl")
            }
          } 
        }
        steps {
          dsl(
            [
              'jobs/bootstrap.groovy'
            ], 
            'DELETE'
            )
        }
      }
